import type { JobCategory, JobCategoryChip, JobPosting } from "@/types/jobs";

export const MOCK_JOBS: JobPosting[] = [
  {
    id: "flt-ops-analyst",
    title: "Analista de Operaciones de Vuelo",
    company: "LATAM Airlines",
    companyMonogram: "LA",
    location: "Lima, Perú",
    locationMode: "On-site",
    jobType: "Full-time",
    category: "Operations",
    salaryMin: 3200,
    salaryMax: 4200,
    postedLabel: "Hace 5 min",
    postedDaysAgo: 0,
    description:
      "Coordina la planificación diaria de la operación, optimiza recursos de flota y asegura la puntualidad de la red de vuelos junto a los centros de control.",
    tags: ["Operations", "On-site"],
    appliedCount: 34,
    featured: false,
  },
  {
    id: "senior-product-designer",
    title: "Senior Product Designer",
    company: "LATAM Digital",
    companyMonogram: "LD",
    location: "Remoto — LATAM",
    locationMode: "Remote",
    jobType: "Full-time",
    category: "Technology",
    salaryMin: 4000,
    salaryMax: 5500,
    postedLabel: "Hace 7 min",
    postedDaysAgo: 0,
    description:
      "Diseña experiencias de clase mundial para millones de pasajeros. Liderarás la investigación, prototipado y sistema de diseño de los productos digitales de LATAM.",
    tags: ["Technology", "Remote"],
    appliedCount: 58,
    featured: true,
  },
  {
    id: "marketing-manager",
    title: "Marketing Manager",
    company: "LATAM Pass",
    companyMonogram: "LP",
    location: "São Paulo, Brasil",
    locationMode: "Hybrid",
    jobType: "Full-time",
    category: "Commercial",
    salaryMin: 3000,
    salaryMax: 4000,
    postedLabel: "Hace 10 min",
    postedDaysAgo: 0,
    description:
      "Impulsa la estrategia de fidelización de LATAM Pass, liderando campañas regionales y elevando el engagement del programa de viajeros frecuentes.",
    tags: ["Commercial", "Hybrid"],
    appliedCount: 21,
    featured: false,
  },
  {
    id: "cabin-crew",
    title: "Tripulante de Cabina",
    company: "LATAM Airlines",
    companyMonogram: "LA",
    location: "Cusco, Perú",
    locationMode: "On-site",
    jobType: "Full-time",
    category: "Customer Experience",
    salaryMin: 1800,
    salaryMax: 2600,
    postedLabel: "Hace 1 día",
    postedDaysAgo: 1,
    description:
      "Brinda una experiencia segura y memorable a bordo. Buscamos personas orientadas al servicio, con dominio de idiomas y pasión por la aviación.",
    tags: ["Customer Experience", "On-site"],
    appliedCount: 112,
    featured: false,
  },
  {
    id: "data-engineer",
    title: "Data Engineer",
    company: "LATAM Digital",
    companyMonogram: "LD",
    location: "Remoto — LATAM",
    locationMode: "Remote",
    jobType: "Freelance",
    category: "Technology",
    salaryMin: 3500,
    salaryMax: 5000,
    postedLabel: "Hace 2 días",
    postedDaysAgo: 2,
    description:
      "Construye pipelines de datos que alimentan decisiones comerciales y operacionales en tiempo real sobre GCP, BigQuery y Firestore.",
    tags: ["Technology", "Remote"],
    appliedCount: 47,
    featured: false,
  },
  {
    id: "finance-intern",
    title: "Practicante de Finanzas",
    company: "LATAM Airlines",
    companyMonogram: "LA",
    location: "Bogotá, Colombia",
    locationMode: "Hybrid",
    jobType: "Internship",
    category: "Finance",
    salaryMin: 900,
    salaryMax: 1400,
    postedLabel: "Hace 4 días",
    postedDaysAgo: 4,
    description:
      "Apoya al equipo de planificación financiera en análisis de costos, reportería y control presupuestario de la operación regional.",
    tags: ["Finance", "Hybrid"],
    appliedCount: 73,
    featured: false,
  },
  {
    id: "talent-partner",
    title: "Talent Acquisition Partner",
    company: "LATAM People",
    companyMonogram: "LP",
    location: "Santiago, Chile",
    locationMode: "Hybrid",
    jobType: "Full-time",
    category: "People",
    salaryMin: 2600,
    salaryMax: 3600,
    postedLabel: "Hace 6 días",
    postedDaysAgo: 6,
    description:
      "Lidera procesos de selección end-to-end para las áreas corporativas, cuidando la experiencia del candidato y la marca empleadora de LATAM.",
    tags: ["People", "Hybrid"],
    appliedCount: 29,
    featured: false,
  },
  {
    id: "sustainability-volunteer",
    title: "Voluntario/a Programa Sostenibilidad",
    company: "Fundación LATAM",
    companyMonogram: "FL",
    location: "Remoto — LATAM",
    locationMode: "Remote",
    jobType: "Volunteer",
    category: "Operations",
    salaryMin: 0,
    salaryMax: 0,
    postedLabel: "Hace 12 días",
    postedDaysAgo: 12,
    description:
      "Súmate a las iniciativas de reforestación y economía circular de LATAM, apoyando la coordinación de proyectos con comunidades de la región.",
    tags: ["Operations", "Remote"],
    appliedCount: 15,
    featured: false,
  },
];

export const buildCategoryChips = (jobs: JobPosting[]): JobCategoryChip[] => {
  const counts = new Map<JobCategory, number>();
  jobs.forEach((job) => {
    counts.set(job.category, (counts.get(job.category) ?? 0) + 1);
  });
  return Array.from(counts.entries()).map(([label, count]) => ({ label, count }));
};
